# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Posts
    url: '/post'
    weight: 20
  - name: Categoties
    url: '/categories'
    weight: 30
  - name: Tags
    url: '/tag'
    weight: 40
  - name: Wiki
    url: 'https://wiki.tgc54.com/en/'
    weight: 50


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
